### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Vicariat** [fowlerwill/tab-finder#1]
Love this plug in.  For me its missing 3 things I personally would value.  I have to use additional plugins for them.
1. Ability to display tabs either in ORDER of occurrence, OR Alphabetical.  To help when I have very large numbers open. Currently it seems kinda random order.  This is my main request.
2. Display the NUMBER of open tabs.
3. Ability to copy the text (as currently displayed) of one or all to clipboard.

Regardless, Thanks for your efforts.

**Comment by fowlerwill** [comment]
Hi Vicariat! Glad to hear you like the plugin :D I'll take a look at what I can do for requests 1 & 2, 

For #3 can you expand on what text you'd like to be copied? A screenshot may help explain.

Thank you, and I'll keep you posted

**Comment by Vicariat** [comment]
Thanks for considering this request!
For point #3, my request is intended to be really simple to state.  The idea is to be able to copy the complete list of displayed text to clipboard as plain text.  What is displayed is a list of all the tab titles.  What is already displayed on the screen is exactly what I'd like copied as text.  Ie a list of the open tabs.  Copied to clipboard in the order shown (which currently seems random) OR in the order selected in point #1.
There are plugins that already do this (hence a lower priority request than my other 2 points).  But it seems easier to have an all-in-one via you.  One example is "Copy All Tabs is a Firefox Add-on that takes the address and title for each tab and creates a text list of links. The list is copied to your clipboard so you can paste it to notes."  The difference on your case, would be to copy the list in the displayed order (ie order of tab occurrence, vs Alphabetical).

**Comment by sergeevabc** [comment]
Typing title of the current page does not display it in the list, which is frustrating.

**Comment by Vicariat** [comment]
@sergeevabc   I see what you mean, but cannot imagine where I would need it to show the CURRENT page, which I am already looking at.  Don't see how that could be frustrating.   I can already see the title in the page header.  Maybe your setup is different?  Maybe simply enable the firefox function that displays the page title at the top (I have always had it on)?  Its somewhere in options I believe.

Not sure why you hijacked this topic instead of starting a new one for this unrelated issue.

**Comment by sergeevabc** [comment]
@Vicariat, screen space is scarce on _laptops_, that’s why _default_ FF outlook with title bar switched off is especially handy. Then one day you have too many opened tabs with obviously shortened titles (e.g. while exploring various add-ons on Mozilla or learning adjacent topics on Wikipedia) and you’re in the middle of some page, not remembering whether it is the very one. That’s the scenario to expand your imagination.

P.S. Ah, the beloved [Fast Tab Switcher][1] is already ported to Webextensions. Be sure to take a peek.

[1]: https://addons.mozilla.org/en-US/firefox/addon/fast-tab-switcher/
